version: '2'
services:
    caseviewer1-app:
        image: caseviewer1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://caseviewer1-mysql:3306/caseviewer1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    caseviewer1-mysql:
        extends:
            file: mysql.yml
            service: caseviewer1-mysql
